version: '3.8'
services:

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_DB: stream_scrape
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # ports:
    #   - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  streamscrape:
    image: stream_scrape:stream_scrape_1.0.0
    container_name: stream_scrape
    build:
      context: .
      # dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    env_file:
      - ./env/dev.env
    command: streamlit run ./scripts/main_st.py --server.port=8502

  airflow:
    image: apache/airflow:2.0.2
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:password@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./scripts:/usr/local/airflow/scripts
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin12345 --firstname Adminfirst --lastname Adminlast --role Admin --email admin@example.com &&
      airflow webserver"

  airflow_scheduler:
    image: apache/airflow:2.0.2
    container_name: airflow_scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:password@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./scripts:/usr/local/airflow/scripts
    command: >
      bash -c "airflow scheduler"
    depends_on:
      - airflow


volumes:
  pg_data:
  pgadmin_data:
